### ISSUE TITLE
filter keys not shown, and one of my 20 or so filters not working.

### ISSUE THREAD

**Issue by shanness** [psethwick/tuidoist#6]
I figured out how to debug it :computer: 

The below is the only filter of about 20 or so of mine that isn't working.
And also, it took me a while to figure out I had to hit **g** then **f** to get filters showing.  Might be worth adding "**/**" for it too from the home screen (same as the web app)?  Or at least documenting it?
I've added a LF below, it's not in the filter.

```
craig@home:~/bin (master)$ DEBUG=1 tuidoist
craig@home:~/bin (master)$ more debug.log 
debug 2024/04/20 10:15:53 0 {isAll:false name: section:Rnr}
debug 2024/04/20 10:15:57 0 {error:syntax error}
debug 2024/04/20 10:15:57 error {syntax error}
```
`( due after: -5 days & due before: +5 days  & created after: -30days ) | ( p1 & (overdue | due before: +5 days))`

**Comment by psethwick** [comment]
I probably _should_ document the keys properly in the README yeah. Fwiw `g?` shows help for the `g` submenu, but it is not really discoverable enough.

I'll see where that filter is broken (I suspect I missed a case of 'date math' on due/created before/after)

edit: minimal recreation: `created after: -30days`  breaks it on its own

**Comment by psethwick** [comment]
the syntax error is definitely fixed, let me know if your filter works as expected!

**Comment by shanness** [comment]
Excellent, that fixed it, thanks!
